export interface MediaItem {
  id: string;
  url: string;
  kind: "IMAGE" | "VIDEO";
  originalName: string;
}

const p = (t: string) => `<p>${t}</p>`;
const ul = (items: string[]) => `<ul>${items.map((i) => `<li>${i}</li>`).join("")}</ul>`;
const h = (t: string) => `<h2>${t}</h2>`;

export const FALLBACK_SPECIALTIES = [
  {
    id: "spec-1",
    title: "Diabetology & Endocrinology",
    slug: "diabetology-and-endocrinology",
    shortSummary: "Comprehensive management of Type 1, Type 2, and gestational diabetes, thyroid disorders, and metabolic health led by Dr. D. Narayana Murthy.",
    contentHtml:
      h("Advanced Diabetes & Endocrine Care") +
      p("Led by Dr. D. Narayana Murthy, MD, our diabetology clinic delivers personalized metabolic care aimed at optimal glucose control, diabetic neuropathy and nephropathy prevention, and thyroid regulation.") +
      ul([
        "Blood glucose and continuous HbA1c screening",
        "Diabetic foot care, neuropathy, and nephropathy prevention",
        "Gestational diabetes screening and maternal metabolic support",
        "Thyroid disorders and comprehensive hormone evaluation",
      ]),
    sortOrder: 0,
    media: [
      { id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" },
      { id: "m-glucose-meter", url: "/seed/glucose-meter.webp", kind: "IMAGE" as const, originalName: "glucose-meter.webp" },
    ],
  },
  {
    id: "spec-2",
    title: "General Medicine",
    slug: "general-medicine",
    shortSummary: "Holistic diagnosis and therapeutic care for acute fevers, chronic hypertension, respiratory ailments, seasonal infections, and multi-system illness.",
    contentHtml:
      h("Expert Primary and Internal Medical Care") +
      p("Our general physicians provide comprehensive outpatient and inpatient clinical care for viral illnesses, respiratory infections, hypertension, digestive issues, and joint pains.") +
      ul([
        "Acute illness diagnosis and hospital observation care",
        "Hypertension, cardiovascular evaluation, and lifestyle plans",
        "Respiratory congestion, bronchial conditions, and asthma management",
        "Infectious diseases including Dengue, Typhoid, and Malaria",
      ]),
    sortOrder: 1,
    media: [
      { id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" },
      { id: "m-opd-waiting", url: "/seed/rithanya-hospital-khammam-outpatient-waiting-area-registration.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-outpatient-waiting-area-registration.webp" },
    ],
  },
  {
    id: "spec-3",
    title: "Gynecology & Women's Health",
    slug: "gynecology-and-womens-health",
    shortSummary: "Comprehensive healthcare for women covering obstetrics, menstrual disorders, gestational monitoring, anaemia management, and wellness.",
    contentHtml:
      h("Compassionate Care for Women & Mothers") +
      p("Dedicated outpatient consultations and screening services for women of all age groups, offering reproductive wellness, antenatal guidance, nutritional anaemia correction, and hormonal balance.") +
      ul([
        "Antenatal checkups and high-risk pregnancy monitoring",
        "Anaemia screening and nutritional replenishment therapy",
        "Menstrual disorder management and hormonal evaluations",
        "Visiting consultant specialist panels for advanced obstetrics",
      ]),
    sortOrder: 2,
    media: [
      { id: "m-child-plant", url: "/seed/rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp" },
      { id: "m-children-day", url: "/seed/rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp" },
    ],
  },
  {
    id: "spec-4",
    title: "Nephrology & Renal Care Management",
    slug: "nephrology-and-renal-care-management",
    shortSummary: "Advanced screening, management, and treatment for kidney stones, acute renal conditions, diabetic nephropathy, and fluid electrolyte balance.",
    contentHtml:
      h("Kidney Health and Renal Protection") +
      p("Focused clinical protocols for kidney health preservation, managing kidney stones, dysuria, urinary tract burning sensations, and chronic kidney disease management.") +
      ul([
        "Kidney stone evaluation, medication, and referral coordination",
        "Diabetic kidney disease screening with microalbuminuria tests",
        "Urinary burning sensation, dysuria, and UTI treatment",
        "Serum creatinine, electrolyte, and renal ultrasound review",
      ]),
    sortOrder: 3,
    media: [
      { id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" },
      { id: "m-lab-microscope", url: "/seed/lab-microscope.webp", kind: "IMAGE" as const, originalName: "lab-microscope.webp" },
    ],
  },
];

export const FALLBACK_SERVICES = [
  {
    id: "serv-1",
    title: "24/7 Emergency Care Services",
    slug: "24-7-emergency-care-services",
    category: "Emergency",
    shortSummary: "Round-the-clock emergency medical triage, observation beds, acute poisoning treatment, trauma stabilization, and critical response.",
    contentHtml:
      h("Always Ready Emergency Wing") +
      p("Operating 24 hours a day, 7 days a week, Rithanya Hospital's emergency desk delivers rapid response for chest pain, respiratory distress, acute poisoning, snake bite/scorpion stings, and high fevers.") +
      ul([
        "24/7 emergency clinical triage and trauma stabilization",
        "Emergency intravenous hydration and observation beds",
        "Acute poisoning treatment and envenomation protocol",
        "Direct standby coordination with 24-hour blood bank and pharmacy",
      ]),
    sortOrder: 0,
    media: [
      { id: "m-building-ext", url: "/seed/rithanya-hospital-khammam-building-exterior-signboard.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-building-exterior-signboard.webp" },
      { id: "m-main-entrance", url: "/seed/rithanya-hospital-khammam-main-entrance-reception.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-main-entrance-reception.webp" },
    ],
  },
  {
    id: "serv-2",
    title: "24-Hour In-House Blood Bank (Rithanya Blood Bank)",
    slug: "24-hour-in-house-blood-bank-rithanya-blood-bank",
    category: "Blood Bank",
    shortSummary: "24-hour licensed in-house blood storage, testing, voluntary blood donation camp operations, and emergency cross-matching services.",
    contentHtml:
      h("Round-the-Clock Blood Banking") +
      p("Rithanya Blood Bank operates 24 hours a day, maintaining whole blood and component stocks for emergencies, elective surgeries, and pediatric transfusion support.") +
      ul([
        "Continuous availability of tested, screened whole blood and components",
        "Emergency compatibility cross-matching with rapid turnaround",
        "Support for voluntary community blood donation drives and camps",
        "Critical alert monitoring with transparent real-time availability",
      ]),
    sortOrder: 1,
    media: [
      { id: "m-blood-donation", url: "/seed/blood-donation.webp", kind: "IMAGE" as const, originalName: "blood-donation.webp" },
      { id: "m-blood-bag", url: "/seed/blood-bag.webp", kind: "IMAGE" as const, originalName: "blood-bag.webp" },
      { id: "m-blood-beds", url: "/seed/blood-beds.webp", kind: "IMAGE" as const, originalName: "blood-beds.webp" },
    ],
  },
  {
    id: "serv-3",
    title: "Aarogyasri Scheme Facility (Specialized care for Pediatric Sickle Cell Anemia and Thalassemia)",
    slug: "aarogyasri-scheme-facility-sickle-cell-thalassemia",
    category: "Government Schemes",
    shortSummary: "Government-empaneled Aarogyasri facility providing specialized care, scheduled daycare blood transfusions, and chelation monitoring for children.",
    contentHtml:
      h("Humanitarian Daycare for Children") +
      p("Rithanya Hospital is proud to provide dedicated humanitarian care under the Aarogyasri scheme, ensuring children with Thalassemia Major and Sickle Cell Anemia receive regular, safe transfusions in a sanitised, caring environment.") +
      ul([
        "Cashless daycare blood transfusions under Aarogyasri scheme",
        "Pediatric iron chelation monitoring and regular ferritin tracking",
        "Bedside nursing with blood warming equipment and saline flushes",
        "Nutritional counseling and moral support for families",
      ]),
    sortOrder: 2,
    media: [
      { id: "m-children-day", url: "/seed/rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp" },
      { id: "m-child-gift", url: "/seed/rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp" },
    ],
  },
  {
    id: "serv-4",
    title: "Outpatient and Inpatient Clinical Consultations",
    slug: "outpatient-and-inpatient-clinical-consultations",
    category: "Clinical Consultations",
    shortSummary: "Comfortable OPD consultation suites, dedicated registration, computerized case files, and attentive inpatient observation care.",
    contentHtml:
      h("Comprehensive Clinical Consultations") +
      p("Patient-centric consultations with experienced physicians, offering detailed clinical evaluations, diagnostic interpretation, computerized prescriptions, and comfortable observation wards.") +
      ul([
        "Unhurried consultations with senior physicians and specialists",
        "Wheelchair-accessible waiting lounges and digital registration desk",
        "Inpatient observation beds with continuous vitals monitoring",
        "Direct connection to on-site diagnostics and pharmacy",
      ]),
    sortOrder: 3,
    media: [
      { id: "m-opd-waiting", url: "/seed/rithanya-hospital-khammam-outpatient-waiting-area-registration.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-outpatient-waiting-area-registration.webp" },
      { id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" },
    ],
  },
];

export const FALLBACK_TREATMENTS = [
  {
    id: "tr-1",
    title: "Blood Pressure / Hypertension (బి.పి.)",
    slug: "blood-pressure-hypertension-bp",
    category: "General Medicine",
    isFlagship: true,
    shortSummary: "Continuous blood pressure monitoring, cardiovascular risk assessment, medication tuning, and long-term hypertension management.",
    contentHtml: h("Hypertension Care & Monitoring") + p("Expert diagnosis, continuous blood pressure monitoring, and tailored medical regimens to protect heart, kidney, and brain health.") + ul(["Targeted BP management plans", "Cardiovascular and renal screening", "Lifestyle and sodium reduction counseling", "Periodic review and medication optimization"]),
    sortOrder: 1,
    media: [{ id: "m-nurse-bp", url: "/seed/nurse-bp.webp", kind: "IMAGE" as const, originalName: "nurse-bp.webp" }],
  },
  {
    id: "tr-2",
    title: "Diabetes / Sugar Management (షుగర్)",
    slug: "diabetes-sugar-management",
    category: "Diabetology & Endocrinology",
    isFlagship: true,
    shortSummary: "Comprehensive management of Type 1, Type 2, and gestational diabetes with HbA1c tracking and organ protection protocols.",
    contentHtml: h("Personalized Diabetes Management") + p("Led by Dr. D. Narayana Murthy, MD, our diabetes clinic focuses on tight glycemic control, complication prevention, and patient education.") + ul(["Fasting, post-prandial, and HbA1c tracking", "Diabetic neuropathy and retinopathy screening", "Dietary and exercise counseling", "Emergency management of hypo/hyperglycemia"]),
    sortOrder: 2,
    media: [{ id: "m-glucose-meter", url: "/seed/glucose-meter.webp", kind: "IMAGE" as const, originalName: "glucose-meter.webp" }, { id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "tr-3",
    title: "Asthma & Bronchial Conditions (అస్తమా / ఉబ్బసం)",
    slug: "asthma-bronchial-conditions",
    category: "Respiratory Medicine",
    isFlagship: false,
    shortSummary: "Nebulization therapy, inhaler optimization, allergy trigger management, and emergency bronchospasm stabilization.",
    contentHtml: h("Comprehensive Asthma Relief") + p("Rapid nebulization, bronchodilator optimization, and personalized asthma action plans to prevent acute flare-ups.") + ul(["Immediate in-clinic nebulization", "Peak flow assessment and inhaler technique guidance", "Allergen trigger identification", "Preventive long-term maintenance protocols"]),
    sortOrder: 3,
    media: [{ id: "m-doc-vitals", url: "/seed/doctor-vitals.webp", kind: "IMAGE" as const, originalName: "doctor-vitals.webp" }],
  },
  {
    id: "tr-4",
    title: "Respiratory Congestion / Phlegm & Fluid in Lungs (ఊపిరితిత్తులలో నెమ్ము)",
    slug: "respiratory-congestion-phlegm-fluid-lungs",
    category: "Respiratory Medicine",
    isFlagship: false,
    shortSummary: "Clinical evaluation of chest congestion, sputum analysis, pulmonary infection treatment, and fluid balance control.",
    contentHtml: h("Chest Congestion & Pulmonary Care") + p("Prompt evaluation of acute lung congestion, chest X-ray correlation, antibiotic therapy when indicated, and mucus clearance assistance.") + ul(["Chest auscultation and digital radiography review", "Targeted expectorants and mucolytic therapy", "Observation bed monitoring with pulse oximetry", "Post-infection pulmonary recovery guidance"]),
    sortOrder: 4,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
  {
    id: "tr-5",
    title: "Breathlessness / Dyspnea (ఆయాసం)",
    slug: "breathlessness-dyspnea",
    category: "Respiratory & Cardiovascular",
    isFlagship: false,
    shortSummary: "Emergency triage for acute shortness of breath, oxygen therapy, cardiovascular/pulmonary differentiation, and rapid relief.",
    contentHtml: h("Emergency Evaluation of Breathlessness") + p("Immediate SpO2 saturation checks, oxygen support, cardiac vs pulmonary etiology diagnosis, and stabilizing medication.") + ul(["Instant high-flow oxygen administration", "ECG and cardiac enzyme screening", "Nebulization and diuretic management when needed", "Careful inpatient observation"]),
    sortOrder: 5,
    media: [{ id: "m-doc-vitals", url: "/seed/doctor-vitals.webp", kind: "IMAGE" as const, originalName: "doctor-vitals.webp" }],
  },
  {
    id: "tr-6",
    title: "Cough & Cold (దగ్గు, జలుబు)",
    slug: "cough-and-cold",
    category: "General Medicine",
    isFlagship: false,
    shortSummary: "Symptomatic and therapeutic treatment for acute upper respiratory infections, allergic rhinitis, and dry/productive cough.",
    contentHtml: h("Upper Respiratory Infection Care") + p("Accurate differentiation between viral and bacterial causes, antihistamines, decongestants, and soothing throat care.") + ul(["Sore throat and nasal congestion relief", "Allergy evaluation and avoidance advice", "Targeted cough suppressants or expectorants", "Preventive immune-supporting guidance"]),
    sortOrder: 6,
    media: [{ id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" }],
  },
  {
    id: "tr-7",
    title: "Gastric Trouble & Indigestion (గ్యాస్ ట్రబుల్)",
    slug: "gastric-trouble-indigestion",
    category: "Gastroenterology",
    isFlagship: false,
    shortSummary: "Treatment for bloating, functional dyspepsia, abdominal fullness, dietary intolerances, and gastrointestinal distress.",
    contentHtml: h("Digestive Wellness & Relief") + p("Modern medical management for chronic gas, belching, indigestion, and gut motility disorders.") + ul(["Gastrointestinal motility evaluation", "Helicobacter pylori and ulcer screening", "Enzymatic and prokinetic therapy", "Personalized dietary modification plans"]),
    sortOrder: 7,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "tr-8",
    title: "Epilepsy / Seizures / Fits (ఫిట్స్ / మూర్ఛవ్యాధి)",
    slug: "epilepsy-seizures-fits",
    category: "Neurology",
    isFlagship: false,
    shortSummary: "Anticonvulsant therapy, seizure emergency stabilization, post-ictal care, and ongoing neurological management.",
    contentHtml: h("Seizure Management & Neurological Care") + p("Emergency response for active seizures, long-term anti-epileptic drug optimization, and family safety education.") + ul(["Emergency anticonvulsant administration", "Diagnostic EEG/imaging coordination", "Drug level monitoring and compliance support", "Seizure first aid education for families"]),
    sortOrder: 8,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
  {
    id: "tr-9",
    title: "Joint Pains (జాయింట్ నొప్పులు)",
    slug: "joint-pains",
    category: "Orthopedics & Rheumatology",
    isFlagship: false,
    shortSummary: "Diagnostic assessment of joint pain, anti-inflammatory treatment, mobility restoration, and arthritis prevention.",
    contentHtml: h("Relief from Painful Joints") + p("Evaluation of acute and chronic joint discomfort, uric acid testing for gout, inflammatory markers, and therapeutic exercise guidance.") + ul(["Serum uric acid, ESR, and RA factor screening", "Targeted anti-inflammatory pain management", "Joint mobility and rehabilitation guidance", "Long-term cartilage protection strategies"]),
    sortOrder: 9,
    media: [{ id: "m-nurse-care", url: "/seed/nurse-care.webp", kind: "IMAGE" as const, originalName: "nurse-care.webp" }],
  },
  {
    id: "tr-10",
    title: "Nocturnal Muscle Cramps & Sleep-related Muscle Pains (నిద్రలో కండరాల నొప్పులు)",
    slug: "nocturnal-muscle-cramps-sleep-pains",
    category: "General Medicine",
    isFlagship: false,
    shortSummary: "Electrolyte imbalance correction, magnesium/calcium therapy, peripheral circulation checks, and nighttime cramp prevention.",
    contentHtml: h("Relief from Nighttime Muscle Spasms") + p("Thorough evaluation of mineral levels, hydration balance, venous circulation, and peripheral neuropathy causing nighttime cramps.") + ul(["Serum calcium, magnesium, and electrolyte testing", "Peripheral arterial and venous screening", "Targeted muscle relaxant and mineral therapy", "Pre-bedtime stretching and hydration plans"]),
    sortOrder: 10,
    media: [{ id: "m-nurse-injection", url: "/seed/nurse-injection.webp", kind: "IMAGE" as const, originalName: "nurse-injection.webp" }],
  },
  {
    id: "tr-11",
    title: "Neuropathy & Nerve Weakness (నరముల బలహీనత)",
    slug: "neuropathy-nerve-weakness",
    category: "Neurology & Endocrinology",
    isFlagship: false,
    shortSummary: "Diabetic neuropathy care, vitamin B12 deficiency correction, neurotrophic therapy, and nerve conduction assessment.",
    contentHtml: h("Nerve Health & Neuropathy Care") + p("Specialized treatment for burning feet, tingling sensations, loss of protective sensation, and diabetic nerve damage.") + ul(["Monofilament and vibration sensory testing", "High-potency neurotrophic vitamin therapy", "Blood sugar stabilization to halt nerve decline", "Fall prevention and neuropathic footwear advice"]),
    sortOrder: 11,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "tr-12",
    title: "Snake Bite & Scorpion Sting Emergency Management (పాముకాటు, తేలుకాటు)",
    slug: "snake-bite-scorpion-sting-emergency",
    category: "Emergency Care",
    isFlagship: true,
    shortSummary: "24/7 emergency protocol with Anti-Snake Venom (ASV), local wound neutralization, coagulation tracking, and ICU observation.",
    contentHtml: h("Critical 24/7 Envenomation Care") + p("Life-saving emergency protocol with polyvalent Anti-Snake Venom (ASV), whole blood clotting tests (WBCT), and venom neutralization.") + ul(["Immediate ASV infusion under intensive monitoring", "20-minute whole blood clotting time tracking", "Anaphylaxis preparedness and respiratory support", "Scorpion sting pain management and cardioprotection"]),
    sortOrder: 12,
    media: [{ id: "m-emergency-bldg", url: "/seed/rithanya-hospital-khammam-building-exterior-signboard.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-building-exterior-signboard.webp" }],
  },
  {
    id: "tr-13",
    title: "Acute Poisoning Treatment (పాయిజనింగ్)",
    slug: "acute-poisoning-treatment",
    category: "Emergency Care",
    isFlagship: true,
    shortSummary: "Gastric lavage, chemical antidotes, atropinization protocols, and intensive resuscitation for acute poisoning cases.",
    contentHtml: h("Emergency Poisoning Response") + p("Rapid toxicological decontamination, emergency gastric lavage, specific antidotes (e.g. Atropine, PAM for organophosphates), and hemodynamic support.") + ul(["Immediate gastric lavage and activated charcoal", "Specific antidote administration protocols", "Airway protection and mechanical ventilation standby", "Continuous ICU observation beds"]),
    sortOrder: 13,
    media: [{ id: "m-doc-vitals", url: "/seed/doctor-vitals.webp", kind: "IMAGE" as const, originalName: "doctor-vitals.webp" }],
  },
  {
    id: "tr-14",
    title: "Jaundice & Hepatic Disorders (కామెర్లు)",
    slug: "jaundice-hepatic-disorders",
    category: "Gastroenterology & Hepatology",
    isFlagship: false,
    shortSummary: "Liver function testing, viral hepatitis serology, hepatoprotective medical therapy, and dietary jaundice rehabilitation.",
    contentHtml: h("Liver Disease & Jaundice Management") + p("Comprehensive diagnostic workup for yellowing of eyes/skin, elevated bilirubin, viral hepatitis, and fatty liver disease.") + ul(["Total/direct bilirubin and liver enzyme panels", "Viral hepatitis A, B, C, E screening", "Hepatoprotective medical support", "Nutritional recovery guidance and hydration"]),
    sortOrder: 14,
    media: [{ id: "m-lab-microscope", url: "/seed/lab-microscope.webp", kind: "IMAGE" as const, originalName: "lab-microscope.webp" }],
  },
  {
    id: "tr-15",
    title: "Chest Pain Evaluation & Heart Care (గుండెనొప్పి)",
    slug: "chest-pain-evaluation-heart-care",
    category: "Cardiovascular & Emergency",
    isFlagship: true,
    shortSummary: "Immediate 12-lead ECG, troponin cardiac biomarkers, emergency stabilization, and cardiovascular referral coordination.",
    contentHtml: h("Immediate Chest Pain Evaluation") + p("Prompt clinical triage for chest pressure, radiating pain, and angina to exclude acute myocardial infarction and stabilize hemodynamics.") + ul(["Immediate 12-lead digital ECG recording", "Rapid cardiac biomarker (Troponin) testing", "Sublingual nitrates, antiplatelets, and oxygen therapy", "Continuous ECG and hemodynamics monitoring"]),
    sortOrder: 15,
    media: [{ id: "m-doc-vitals", url: "/seed/doctor-vitals.webp", kind: "IMAGE" as const, originalName: "doctor-vitals.webp" }],
  },
  {
    id: "tr-16",
    title: "Gastric Burning / Acidity (కడుపులో మంట)",
    slug: "gastric-burning-acidity",
    category: "Gastroenterology",
    isFlagship: false,
    shortSummary: "Proton-pump inhibitor therapy, mucosal healing, acid reflux suppression, and ulcer prevention.",
    contentHtml: h("Relief from Heartburn & Acidity") + p("Targeted acid suppression, gastro-esophageal reflux (GERD) control, and mucosal protective agents for burning pain.") + ul(["Advanced PPI and H2 receptor blocker regimens", "Mucosal coating and antacid formulations", "Dietary trigger identification and meal timing guidance", "Gastritis and peptic ulcer healing monitoring"]),
    sortOrder: 16,
    media: [{ id: "m-pharmacy-counter", url: "/seed/pharmacy-counter.webp", kind: "IMAGE" as const, originalName: "pharmacy-counter.webp" }],
  },
  {
    id: "tr-17",
    title: "Dizziness & Vertigo (తల తిరుగుట)",
    slug: "dizziness-and-vertigo",
    category: "General Medicine & ENT",
    isFlagship: false,
    shortSummary: "Inner ear canalith repositioning, vestibular sedatives, postural hypotension correction, and cervical vertigo therapy.",
    contentHtml: h("Vertigo & Balance Care") + p("Accurate differentiation between benign paroxysmal positional vertigo (BPPV), cervical spondylosis, low blood pressure, and labyrinthitis.") + ul(["Dix-Hallpike maneuver and vestibular assessment", "Epley repositioning procedure for BPPV", "Anti-vertigo and neuro-circulatory therapy", "Fall risk counseling and balance exercises"]),
    sortOrder: 17,
    media: [{ id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" }],
  },
  {
    id: "tr-18",
    title: "Numbness & Allergies (తిమ్మిర్లు, ఎలర్జీ)",
    slug: "numbness-and-allergies",
    category: "General Medicine",
    isFlagship: false,
    shortSummary: "Management of extremity paresthesias, allergic urticaria, cutaneous reactions, and systemic antihistaminic therapy.",
    contentHtml: h("Allergy Treatment & Sensation Restoration") + p("Prompt therapy for acute skin rashes, hives, swelling, along with clinical investigation for tingling and numbness.") + ul(["Emergency antiallergic and corticosteroid support", "Peripheral nerve entrapment assessment", "Identification of dietary, drug, and environmental allergens", "Desensitization counseling and safe medication"]),
    sortOrder: 18,
    media: [{ id: "m-nurse-care", url: "/seed/nurse-care.webp", kind: "IMAGE" as const, originalName: "nurse-care.webp" }],
  },
  {
    id: "tr-19",
    title: "Paralysis & Stroke Care (పక్షవాతం)",
    slug: "paralysis-stroke-care",
    category: "Neurology & Emergency",
    isFlagship: true,
    shortSummary: "Emergency acute ischemic stroke stabilization, blood pressure modulation, secondary prevention, and recovery rehabilitation.",
    contentHtml: h("Stroke Care & Neuro-Rehabilitation") + p("Fast-track emergency triage for sudden facial drooping, arm weakness, and slurred speech, coupled with ongoing paralysis recovery.") + ul(["Rapid stroke triage and blood pressure control", "Neuro-protective medical protocols", "Secondary stroke prevention and antiplatelet management", "Long-term mobility support and nursing assistance"]),
    sortOrder: 19,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
  {
    id: "tr-20",
    title: "Kidney Stones & Renal Diseases (కిడ్నీలో రాళ్లు, కిడ్నీ వ్యాధులు)",
    slug: "kidney-stones-renal-diseases",
    category: "Nephrology & Urology",
    isFlagship: true,
    shortSummary: "Renal ultrasound evaluation, stone expulsive therapy, pain management for renal colic, and kidney function preservation.",
    contentHtml: h("Comprehensive Kidney Stone & Renal Care") + p("Emergency relief for severe loin-to-groin colic, medical expulsive therapy for calculi, and long-term renal disease management.") + ul(["Urgent analgesia and hydration for renal colic", "Ultrasonography and urine microscopy evaluation", "Stone expulsive and urine alkalinizing regimens", "Serum creatinine and GFR monitoring"]),
    sortOrder: 20,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
  {
    id: "tr-21",
    title: "Urinary Burning Sensation / Dysuria (మూత్రం మంట)",
    slug: "urinary-burning-sensation-dysuria",
    category: "Nephrology & Urology",
    isFlagship: false,
    shortSummary: "Rapid urine analysis, culture sensitivity, urinary alkalizers, and targeted antibiotic therapy for urinary tract infections.",
    contentHtml: h("Fast Relief for Urinary Infections") + p("Same-day urinalysis to identify pus cells and crystals, soothing alkalinizers, and effective antimicrobial therapy.") + ul(["Rapid dipstick and microscopic urinalysis", "Culture-sensitive antibiotic selection", "Urinary analgesic and alkalizing medications", "Hydration protocols and recurrence prevention"]),
    sortOrder: 21,
    media: [{ id: "m-lab-microscope", url: "/seed/lab-microscope.webp", kind: "IMAGE" as const, originalName: "lab-microscope.webp" }],
  },
  {
    id: "tr-22",
    title: "Dengue Fever (డెంగ్యూ)",
    slug: "dengue-fever",
    category: "Infectious Diseases",
    isFlagship: true,
    shortSummary: "Daily platelet monitoring, hematocrit tracking, intravenous fluid therapy, and in-house blood bank standby for platelets.",
    contentHtml: h("Critical Dengue Care & Platelet Standby") + p("Protocol-based management of dengue hemorrhagic fever, serial complete blood counts, micro-hydration, and in-house blood bank support.") + ul(["NS1 antigen and IgM/IgG antibody serology", "Daily serial platelet and hematocrit monitoring", "Precision IV fluid therapy to prevent shock", "Ready in-house blood and component availability"]),
    sortOrder: 22,
    media: [{ id: "m-blood-donation", url: "/seed/blood-donation.webp", kind: "IMAGE" as const, originalName: "blood-donation.webp" }],
  },
  {
    id: "tr-23",
    title: "Malaria (మలేరియా)",
    slug: "malaria-treatment",
    category: "Infectious Diseases",
    isFlagship: false,
    shortSummary: "Peripheral blood smear examination, rapid antigen testing, artemisinin combination therapy, and fever control.",
    contentHtml: h("Accurate Malaria Diagnosis & Cure") + p("Prompt testing for Plasmodium vivax and falciparum, full-course antimalarials, and monitoring against hemolytic complications.") + ul(["Peripheral smear and rapid card antigen tests", "WHO-guided artemisinin combination regimens", "Temperature regulation and hydration support", "Complete cure verification testing"]),
    sortOrder: 23,
    media: [{ id: "m-lab-microscope", url: "/seed/lab-microscope.webp", kind: "IMAGE" as const, originalName: "lab-microscope.webp" }],
  },
  {
    id: "tr-24",
    title: "Typhoid Fever (టైఫాయిడ్)",
    slug: "typhoid-fever",
    category: "Infectious Diseases",
    isFlagship: false,
    shortSummary: "Widal test, blood culture, targeted antibiotic regimens, gastrointestinal monitoring, and nutritional recovery.",
    contentHtml: h("Definitive Typhoid Management") + p("Careful clinical monitoring for step-ladder fever, intestinal tenderness, antibiotic therapy, and gentle recovery diet plans.") + ul(["Widal and Typhoid IgM rapid serology", "Targeted third-generation cephalosporin regimens", "Observation beds with hydration management", "High-calorie, easily digestible recovery diet guidance"]),
    sortOrder: 24,
    media: [{ id: "m-doc-vitals", url: "/seed/doctor-vitals.webp", kind: "IMAGE" as const, originalName: "doctor-vitals.webp" }],
  },
  {
    id: "tr-25",
    title: "Viral Fevers (వైరల్ జ్వరాలు)",
    slug: "viral-fevers",
    category: "Infectious Diseases",
    isFlagship: false,
    shortSummary: "Symptomatic relief, electrolyte replenishment, paracetamol antipyretic protocols, and clinical rule-out of secondary infections.",
    contentHtml: h("Compassionate Care for Seasonal Viral Fevers") + p("Comprehensive supportive care for seasonal viral illnesses with high fever, body aches, fatigue, and loss of appetite.") + ul(["Accurate diagnostic workup to exclude complications", "Safe, monitored antipyretic therapy", "Oral and intravenous rehydration support", "Follow-up monitoring until full recovery"]),
    sortOrder: 25,
    media: [{ id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" }],
  },
  {
    id: "tr-26",
    title: "COVID-19 Management (కోవిడ్-19)",
    slug: "covid-19-management",
    category: "Infectious Diseases & Pulmonology",
    isFlagship: false,
    shortSummary: "SpO2 saturation monitoring, antiviral and anti-inflammatory protocols, oxygen therapy, and post-COVID pulmonary care.",
    contentHtml: h("Evidence-Based COVID-19 Protocols") + p("Evidence-based management of mild to moderate COVID-19 infection, oxygen saturation monitoring, and post-COVID fatigue rehabilitation.") + ul(["Continuous SpO2 and vitals monitoring", "Targeted anti-inflammatory and antiviral medication", "Oxygen therapy in observation beds", "Post-COVID lung capacity recovery programs"]),
    sortOrder: 26,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
  {
    id: "tr-27",
    title: "Chikungunya (చికెన్ గున్యా)",
    slug: "chikungunya-management",
    category: "Infectious Diseases & Rheumatology",
    isFlagship: false,
    shortSummary: "Management of debilitating post-viral joint pains, swelling, anti-inflammatory therapy, and physical mobility restoration.",
    contentHtml: h("Chikungunya Fever & Joint Pain Care") + p("Specialized medical protocols to combat intense arthralgia and persistent joint swelling following Chikungunya infection.") + ul(["Diagnostic confirmation and antibody testing", "Targeted anti-inflammatory and analgesic regimens", "Gentle physical therapy and stiffness relief", "Long-term recovery and nutritional support"]),
    sortOrder: 27,
    media: [{ id: "m-nurse-care", url: "/seed/nurse-care.webp", kind: "IMAGE" as const, originalName: "nurse-care.webp" }],
  },
  {
    id: "tr-28",
    title: "Anemia / Blood Deficiency (రక్త హీనత)",
    slug: "anemia-blood-deficiency",
    category: "Hematology & Women's Health",
    isFlagship: true,
    shortSummary: "Iron deficiency workup, intravenous iron sucrose/ferric carboxymaltose infusions, nutritional replenishment, and blood transfusions.",
    contentHtml: h("Comprehensive Anemia Evaluation & Correction") + p("Rapid investigation for low hemoglobin, ferritin deficiency, nutritional anemia, and daycare intravenous iron therapy.") + ul(["Complete blood count (CBC) and serum ferritin testing", "Daycare IV iron infusion under nursing supervision", "Dietary counseling high in iron and folate", "Matched packed red cell transfusions for severe anemia"]),
    sortOrder: 28,
    media: [{ id: "m-blood-bag", url: "/seed/blood-bag.webp", kind: "IMAGE" as const, originalName: "blood-bag.webp" }, { id: "m-child-plant", url: "/seed/rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp" }],
  },
  {
    id: "tr-29",
    title: "Thyroid Disorders (థైరాయిడ్)",
    slug: "thyroid-disorders",
    category: "Diabetology & Endocrinology",
    isFlagship: false,
    shortSummary: "TSH, Free T3/T4 testing, levothyroxine dosage optimization for hypothyroidism, hyperthyroidism management, and goiter screening.",
    contentHtml: h("Endocrine Thyroid Care") + p("Precise hormone replacement and suppression therapy for hypothyroidism, hyperthyroidism, weight fluctuations, and fatigue.") + ul(["Sensitive TSH, FT3, and FT4 hormone testing", "Customized levothyroxine dosing and periodic monitoring", "Management of thyroid during pregnancy", "Dietary and lifestyle endocrine support"]),
    sortOrder: 29,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "tr-30",
    title: "General Headaches (తలనొప్పి)",
    slug: "general-headaches",
    category: "General Medicine",
    isFlagship: false,
    shortSummary: "Diagnosis of tension headaches, sinus headaches, eye-strain headaches, blood pressure-related headaches, and pain relief.",
    contentHtml: h("Headache Diagnosis & Effective Relief") + p("Thorough clinical screening to identify the root cause of recurrent headaches, blood pressure checks, and targeted analgesic therapy.") + ul(["Blood pressure and neurological examination", "Sinus and vision screening referrals", "Rapid acute headache relief medication", "Stress reduction and posture correction counseling"]),
    sortOrder: 30,
    media: [{ id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" }],
  },
  {
    id: "tr-31",
    title: "Migraine Headaches (మైగ్రెయిన్ తలనొప్పి)",
    slug: "migraine-headaches",
    category: "Neurology",
    isFlagship: false,
    shortSummary: "Acute migraine abortive therapy, prophylactic medication, trigger avoidance, and light/sound sensitivity management.",
    contentHtml: h("Specialized Migraine Therapy") + p("Dedicated medical management for throbbing unilateral headaches, nausea, aura, and photophobia.") + ul(["Targeted triptan and abortive analgesic therapy", "Daily preventive prophylactic medication plans", "Migraine trigger tracking and lifestyle adjustments", "Darkened quiet observation beds during severe attacks"]),
    sortOrder: 31,
    media: [{ id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" }],
  },
  {
    id: "tr-32",
    title: "Chronic Constipation (మలబద్ధకం)",
    slug: "chronic-constipation",
    category: "Gastroenterology",
    isFlagship: false,
    shortSummary: "Dietary fiber regimens, osmotic laxatives, bowel motility enhancement, and prevention of anorectal fissures and hemorrhoids.",
    contentHtml: h("Gentle & Long-Lasting Bowel Regulation") + p("Clinical management for irregular bowel movements, hard stools, and painful evacuation with gentle therapeutic agents.") + ul(["Colonic motility and dietary fiber assessment", "Safe osmotic and bulk-forming laxatives", "Fluid hydration and gut biome support", "Prevention of secondary fissures and piles"]),
    sortOrder: 32,
    media: [{ id: "m-pharmacy-counter", url: "/seed/pharmacy-counter.webp", kind: "IMAGE" as const, originalName: "pharmacy-counter.webp" }],
  },
  {
    id: "tr-33",
    title: "Rheumatism & Arthritis (కీళ్లవాతం)",
    slug: "rheumatism-and-arthritis",
    category: "Orthopedics & Rheumatology",
    isFlagship: false,
    shortSummary: "Autoimmune arthritis screening, DMARDs, joint inflammation suppression, morning stiffness relief, and mobility protection.",
    contentHtml: h("Arthritis & Rheumatological Care") + p("Expert management for rheumatoid arthritis, osteoarthritic degeneration, joint inflammation, and morning stiffness.") + ul(["RA factor, Anti-CCP, and ESR inflammatory markers", "Disease-modifying antirheumatic therapies (DMARDs)", "Joint-preserving physical exercises", "Anti-inflammatory pain management"]),
    sortOrder: 33,
    media: [{ id: "m-nurse-care", url: "/seed/nurse-care.webp", kind: "IMAGE" as const, originalName: "nurse-care.webp" }],
  },
  {
    id: "tr-34",
    title: "Knee Joint Pain (మోకాళ్ళ నొప్పి)",
    slug: "knee-joint-pain",
    category: "Orthopedics",
    isFlagship: false,
    shortSummary: "Knee osteoarthritis staging, quadriceps strengthening guidance, intra-articular therapies, and pain-free walking support.",
    contentHtml: h("Knee Pain Relief & Mobility Restoration") + p("Targeted therapies for knee pain, cartilage wear-and-tear, difficulty climbing stairs, and weight-bearing support.") + ul(["Weight-bearing digital X-ray review", "Cartilage health and anti-inflammatory therapy", "Quadriceps strengthening and physiotherapy exercises", "Lifestyle and ergonomic joint protection"]),
    sortOrder: 34,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
  {
    id: "tr-35",
    title: "Mental & Psychological Health Issues (మానసిక సమస్యలు)",
    slug: "mental-psychological-health-issues",
    category: "Psychiatry & Psychological Health",
    isFlagship: false,
    shortSummary: "Compassionate clinical consultations, depression and stress screening, medical therapy, and counseling support.",
    contentHtml: h("Confidential Mental Health & Wellness") + p("Sensitive, confidential medical consultations for chronic stress, depression, mood changes, and psychological distress.") + ul(["Confidential, empathetic clinical evaluations", "Medical therapy for anxiety and mood stabilization", "Stress management and coping strategies", "Family counseling and ongoing support"]),
    sortOrder: 35,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "tr-36",
    title: "Insomnia & Sleep Disorders (నిద్ర సమస్యలు)",
    slug: "insomnia-sleep-disorders",
    category: "Psychiatry & Sleep Medicine",
    isFlagship: false,
    shortSummary: "Sleep hygiene protocols, circadian rhythm regulation, non-habit-forming sleep aids, and restorative rest therapy.",
    contentHtml: h("Restful Sleep & Insomnia Treatment") + p("Clinical evaluation for difficulty falling or staying asleep, restless legs, nighttime anxiety, and daytime exhaustion.") + ul(["Sleep cycle and sleep hygiene assessment", "Non-habit-forming therapeutic sleep support", "Screen time and circadian rhythm management", "Treatment of underlying anxiety or physical pain causes"]),
    sortOrder: 36,
    media: [{ id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" }],
  },
  {
    id: "tr-37",
    title: "Memory Loss & Anxiety Disorders (మతిమరుపు, ఆందోళన)",
    slug: "memory-loss-anxiety-disorders",
    category: "Psychiatry & Neurology",
    isFlagship: false,
    shortSummary: "Cognitive assessment, anxiolytic medical support, neuro-nutritional therapy, and dementia screening in seniors.",
    contentHtml: h("Cognitive Care & Anxiety Reduction") + p("Comprehensive evaluation of acute anxiety, panic symptoms, age-related forgetfulness, and cognitive preservation.") + ul(["Mini-mental status and cognitive assessments", "Medical management for generalized anxiety disorder", "Neuroprotective nutrition (B-vitamins, antioxidants)", "Supportive counseling for patients and caregivers"]),
    sortOrder: 37,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "tr-38",
    title: "Neck Pain & Cervical Discomfort (మెడనొప్పులు)",
    slug: "neck-pain-cervical-discomfort",
    category: "Orthopedics & Spine Care",
    isFlagship: false,
    shortSummary: "Cervical spondylosis management, muscle spasm relief, ergonomic posture correction, and cervical collar support.",
    contentHtml: h("Cervical Spine Care & Neck Pain Relief") + p("Relief from neck stiffness, radiating arm pain, computer/mobile posture strain, and degenerative disc issues.") + ul(["Cervical spine examination and X-ray review", "Muscle relaxants and targeted analgesics", "Ergonomic workspace and pillow adjustment guidance", "Isometric neck strengthening exercises"]),
    sortOrder: 38,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
  {
    id: "tr-39",
    title: "Erectile Dysfunction (అంగస్తంభన లేకపోవడం)",
    slug: "erectile-dysfunction",
    category: "Men's Health & Wellness",
    isFlagship: false,
    shortSummary: "Confidential and evidence-based diagnosis, vascular and hormonal evaluation, PDE-5 inhibitors, and lifestyle optimization.",
    contentHtml: h("Confidential Men's Health & Vascular Care") + p("Private, respectful clinical evaluation for erectile dysfunction, addressing vascular health, testosterone levels, diabetes links, and stress factors.") + ul(["Confidential one-on-one medical consultation", "Blood sugar, lipid, and hormone profile screening", "Evidence-based medical therapy (PDE-5 inhibitors)", "Cardiovascular and lifestyle risk factor correction"]),
    sortOrder: 39,
    media: [{ id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" }],
  },
  {
    id: "tr-40",
    title: "Low Libido / Sexual Dysfunction (సెక్స్ కోరికలు తగ్గిపోవడం)",
    slug: "low-libido-sexual-dysfunction",
    category: "Men's Health & Wellness",
    isFlagship: false,
    shortSummary: "Investigation of endocrine deficiencies, chronic fatigue, psychological stress, and revitalizing wellness therapy.",
    contentHtml: h("Hormonal & Sexual Vitality Restoration") + p("Holistic clinical approach investigating hormonal deficiencies, chronic metabolic fatigue, stress, and personalized medical solutions.") + ul(["Comprehensive endocrine and testosterone testing", "Screening for medication-induced sexual side effects", "Vitality enhancement and nutritional support", "Private, judgment-free clinical guidance"]),
    sortOrder: 40,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
];

export const FALLBACK_DOCTORS = [
  {
    id: "doc-1",
    fullName: "Dr. D. Narayana Murthy, M.D., M.S.",
    slug: "dr-d-narayana-murthy-md",
    qualifications: "M.D. (General Physician), M.S. (General Surgery)",
    designation: "Chief Consultant & Medical Director",
    department: "Diabetology & General Medicine",
    consultationTimings: "OPD 9:00 AM – 8:00 PM · Emergency 24/7",
    isVisiting: false,
    experienceYears: 24,
    biographyHtml:
      p("Dr. D. Narayana Murthy (Regd. No. 81187) is the Chief Consultant, Diabetologist, and Medical Director of Rithanya Hospital in Khammam.") +
      p("With over two decades of distinguished clinical experience in internal medicine, surgical evaluation, and diabetology, Dr. Narayana Murthy is recognized across Telangana for his dedicated care and patient-first approach.") +
      p("He directs the hospital's specialized Thalassemia and Sickle Cell Daycare Transfusion Centre and Aarogyasri clinical services."),
    sortOrder: 0,
    media: [
      { id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" },
      { id: "m-doc-room", url: "/seed/rithanya-hospital-khammam-doctor-in-consultation-room.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-in-consultation-room.webp" },
      { id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" },
    ],
  },
  {
    id: "doc-2",
    fullName: "Dr. A. Lakshmi Deepa",
    slug: "dr-a-lakshmi-deepa",
    qualifications: "M.B.B.S.",
    designation: "Co-Founder & Consulting Physician",
    department: "Hospital Leadership & General Medicine",
    consultationTimings: "By appointment",
    isVisiting: false,
    experienceYears: 18,
    biographyHtml: p("Dr. A. Lakshmi Deepa is co-founder of Rithanya Hospital, guiding clinical quality, women's wellness, and the hospital's mission of compassionate healthcare for families in Khammam."),
    sortOrder: 1,
    media: [
      { id: "m-child-care", url: "/seed/rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp" },
    ],
  },
  {
    id: "doc-3",
    fullName: "Visiting Specialist Panel",
    slug: "visiting-specialist-panel",
    qualifications: "Various",
    designation: "Visiting Faculty & Surgeons",
    department: "Obstetrics & Gynaecology · Minimal Access Surgery · Nephrology",
    consultationTimings: "Call 9014444886 / 9492743432 for schedules",
    isVisiting: true,
    experienceYears: 16,
    biographyHtml: p("Consulting specialists in Obstetrics & Gynaecology, Minimal Access Surgery, Nephrology, and Orthopedics visit Rithanya Hospital on scheduled days."),
    sortOrder: 2,
    media: [
      { id: "m-doc-dais", url: "/seed/rithanya-hospital-khammam-speaker-at-dais-floral-backdrop.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-speaker-at-dais-floral-backdrop.webp" },
    ],
  },
];

export const FALLBACK_INSURANCE = [
  {
    id: "ins-1",
    name: "Ayushman Bharat PM-JAY",
    schemeType: "Government Scheme",
    descriptionHtml:
      p("Rithanya Hospital is empaneled under PM-JAY for subsidised, cashless treatment.") +
      ul(["Carry your Ayushman card and a government photo ID", "Visit the cashless desk on arrival", "We assist with pre-authorisation"]),
    sortOrder: 0,
    media: [{ id: "m-logo-pmjay", url: "/seed/logo-pmjay.webp", kind: "IMAGE" as const, originalName: "logo-pmjay.webp" }],
  },
  {
    id: "ins-2",
    name: "Aarogyasri Health Care Trust",
    schemeType: "Government Scheme",
    descriptionHtml:
      p("Our desk helps eligible families navigate Aarogyasri enrolment and claims, especially for pediatric thalassemia and sickle cell care.") +
      ul(["White ration card / Aarogyasri card", "Photo ID of patient", "Referral documents where applicable"]),
    sortOrder: 1,
    media: [{ id: "m-logo-aarogyasri", url: "/seed/logo-aarogyasri.webp", kind: "IMAGE" as const, originalName: "logo-aarogyasri.webp" }],
  },
  {
    id: "ins-3",
    name: "Private Insurance & TPA Cashless",
    schemeType: "Private TPA",
    descriptionHtml:
      p("Private health insurance holders can request cashless pre-authorisation through our billing desk.") +
      ul(["Policy or e-card copy", "Photo ID", "Doctor's admission advice"]),
    sortOrder: 2,
    media: [{ id: "m-logo-tpa", url: "/seed/logo-tpa.webp", kind: "IMAGE" as const, originalName: "logo-tpa.webp" }],
  },
];

export const FALLBACK_GALLERY = [
  {
    id: "gal-1",
    title: "Children's Day celebration at Rithanya Hospital",
    mediaType: "IMAGE",
    caption: "Staff and children celebrate Children's Day at Rithanya Hospital, Khammam.",
    embedCode: "",
    sortOrder: 0,
    media: [{ id: "m-children-day", url: "/seed/rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp" }],
  },
  {
    id: "gal-2",
    title: "Main Entrance and Reception Desk",
    mediaType: "IMAGE",
    caption: "The main glass entrance of Rithanya Hospital, Khammam, with bilingual signage.",
    embedCode: "",
    sortOrder: 1,
    media: [{ id: "m-main-entrance", url: "/seed/rithanya-hospital-khammam-main-entrance-reception.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-main-entrance-reception.webp" }],
  },
  {
    id: "gal-3",
    title: "Outpatient Waiting Lounge & Registration",
    mediaType: "IMAGE",
    caption: "Patients and families in the spacious outpatient waiting area at Rithanya Hospital.",
    embedCode: "",
    sortOrder: 2,
    media: [{ id: "m-opd-waiting", url: "/seed/rithanya-hospital-khammam-outpatient-waiting-area-registration.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-outpatient-waiting-area-registration.webp" }],
  },
  {
    id: "gal-4",
    title: "OPD Consultation with Dr. Narayana Murthy",
    mediaType: "IMAGE",
    caption: "Dr. Narayana Murthy consults a patient in the OPD consultation room.",
    embedCode: "",
    sortOrder: 3,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "gal-5",
    title: "Hospital Building & Exterior View",
    mediaType: "IMAGE",
    caption: "Exterior view of the Rithanya Hospital building on Wyra Road, Khammam.",
    embedCode: "",
    sortOrder: 4,
    media: [{ id: "m-building-ext", url: "/seed/rithanya-hospital-khammam-building-exterior-signboard.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-building-exterior-signboard.webp" }],
  },
  {
    id: "gal-6",
    title: "Free Health Camp Stage in Khammam",
    mediaType: "IMAGE",
    caption: "Doctors, police officials, and medical students addressing the community at a free health camp.",
    embedCode: "",
    sortOrder: 5,
    media: [{ id: "m-camp-stage", url: "/seed/rithanya-hospital-khammam-health-camp-stage-audience.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-health-camp-stage-audience.webp" }],
  },
  {
    id: "gal-7",
    title: "Free Eye Screening & Health Camp Ceremony",
    mediaType: "IMAGE",
    caption: "Free eye checkup camp and health awareness memento presentation in Khammam.",
    embedCode: "",
    sortOrder: 6,
    media: [{ id: "m-eye-camp", url: "/seed/rithanya-hospital-khammam-eye-camp-award-ceremony.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-eye-camp-award-ceremony.webp" }],
  },
  {
    id: "gal-8",
    title: "Hrudaya Spandana Seva Community Programme",
    mediaType: "IMAGE",
    caption: "Doctors, dignitaries and beneficiaries gather for community health recognition in Khammam.",
    embedCode: "",
    sortOrder: 7,
    media: [{ id: "m-hrudaya", url: "/seed/rithanya-hospital-khammam-hrudaya-spandana-seva-stage-group-photo.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-hrudaya-spandana-seva-stage-group-photo.webp" }],
  },
  {
    id: "gal-9",
    title: "Care Beyond Treatment - Pediatric Recovery",
    mediaType: "IMAGE",
    caption: "Doctor and patient celebrate recovery with a potted plant gift at Rithanya Hospital.",
    embedCode: "",
    sortOrder: 8,
    media: [{ id: "m-child-plant", url: "/seed/rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp" }],
  },
  {
    id: "gal-10",
    title: "Eenadu Newspaper Feature - Children's Health Camp",
    mediaType: "IMAGE",
    caption: "Coverage in Eenadu Telugu daily documenting pediatric healthcare initiatives in Khammam.",
    embedCode: "",
    sortOrder: 9,
    media: [{ id: "m-eenadu", url: "/seed/rithanya-hospital-khammam-eenadu-newspaper-clipping-2023.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-eenadu-newspaper-clipping-2023.webp" }],
  },
  {
    id: "gal-11",
    title: "Surya Newspaper Feature - Healthcare Centre Support",
    mediaType: "IMAGE",
    caption: "Press coverage in Surya Telugu daily on health centre initiatives in Khammam district.",
    embedCode: "",
    sortOrder: 10,
    media: [{ id: "m-surya", url: "/seed/rithanya-hospital-khammam-surya-newspaper-clipping-2024.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surya-newspaper-clipping-2024.webp" }],
  },
  {
    id: "gal-12",
    title: "Daycare Transfusion and IV Care in Action",
    mediaType: "VIDEO",
    caption: "A short look at compassionate IV and transfusion nursing care.",
    embedCode: "",
    sortOrder: 11,
    media: [{ id: "m-clip-iv-drip", url: "/seed/clip-iv-drip.mp4", kind: "VIDEO" as const, originalName: "clip-iv-drip.mp4" }],
  },
];

export const FALLBACK_TESTIMONIALS = [
  {
    id: "test-1",
    patientName: "Parent of Thalassemia Patient",
    location: "Khammam",
    treatment: "Thalassemia Daycare Transfusion",
    rating: 5,
    quote: "The nurses attend to my child the moment we arrive and Dr. Narayana Murthy explains everything patiently. Transfusion days are so peaceful and safe here.",
    sortOrder: 0,
    media: [{ id: "m-child-plant", url: "/seed/rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp" }],
  },
  {
    id: "test-2",
    patientName: "Diabetes Patient & Family",
    location: "Wyra Road, Khammam",
    treatment: "Diabetology & Sugar Care",
    rating: 5,
    quote: "Dr. Narayana Murthy gives encouragement along with treatment. My blood sugar and HbA1c are under steady control for the first time in years.",
    sortOrder: 1,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "test-3",
    patientName: "Senior Citizen Visitor",
    location: "Nehru Nagar, Khammam",
    treatment: "General Medicine & Senior Wellness",
    rating: 5,
    quote: "Very clean hospital, easy wheelchair access, attentive staff, and crystal clear billing. Best hospital experience in Khammam.",
    sortOrder: 2,
    media: [{ id: "m-opd-waiting", url: "/seed/rithanya-hospital-khammam-outpatient-waiting-area-registration.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-outpatient-waiting-area-registration.webp" }],
  },
];

export const FALLBACK_BLOGS = [
  {
    id: "blog-1",
    title: "Understanding HbA1c: Your Three-Month Sugar Report Card",
    slug: "understanding-hba1c-your-three-month-sugar-report-card",
    authorName: "Dr. D. Narayana Murthy",
    category: "Diabetes Management",
    excerpt: "HbA1c reflects your average blood sugar over approximately three months. Learn why it is the gold standard for metabolic health.",
    contentHtml:
      h("Why HbA1c Matters") +
      p("Unlike a single fasting finger-prick reading, HbA1c reflects your average glycemic control over the past 90 days. Tracking HbA1c protects your kidneys, eyes, and heart.") +
      ul(["Test HbA1c every 3 to 6 months", "Target under 7% for most non-pregnant adults", "Combine medication with personalized dietary counseling"]),
    isPublished: true,
    publishedAt: new Date("2026-09-15T10:00:00.000Z"),
    sortOrder: 0,
    media: [{ id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" }],
  },
  {
    id: "blog-2",
    title: "Living Well with Thalassemia: A Family Care Guide",
    slug: "living-well-with-thalassemia-a-family-care-guide",
    authorName: "Rithanya Medical Editorial",
    category: "Blood Disorders",
    excerpt: "Essential guide for parents: preparing for transfusion days, monitoring ferritin, and nutritional support for children.",
    contentHtml:
      h("Before You Arrive at Daycare") +
      p("Keep your child well-hydrated, bring previous transfusion reports, and verify pre-transfusion cross-matching for a safe, smooth transfusion.") +
      ul(["Keep up with scheduled transfusions without skipping", "Monitor serum ferritin to assess iron overload", "Maintain oral chelation therapy consistently"]),
    isPublished: true,
    publishedAt: new Date("2026-09-18T10:00:00.000Z"),
    sortOrder: 1,
    media: [{ id: "m-children-day", url: "/seed/rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp" }],
  },
  {
    id: "blog-3",
    title: "Managing Hypertension & Preventing Silent Complications",
    slug: "managing-hypertension-preventing-silent-complications",
    authorName: "Dr. D. Narayana Murthy",
    category: "General Medicine",
    excerpt: "High blood pressure often exhibits no overt symptoms. Discover proactive steps to maintain healthy arterial pressure.",
    contentHtml:
      h("Protecting Your Heart and Kidneys") +
      p("Hypertension is often dubbed the silent condition. Routine blood pressure measurement prevents strokes, kidney damage, and heart complications.") +
      ul(["Check your blood pressure periodically", "Reduce dietary sodium and processed foods", "Take prescribed antihypertensive medication regularly"]),
    isPublished: true,
    publishedAt: new Date("2026-09-22T10:00:00.000Z"),
    sortOrder: 2,
    media: [{ id: "m-nurse-bp", url: "/seed/nurse-bp.webp", kind: "IMAGE" as const, originalName: "nurse-bp.webp" }],
  },
  {
    id: "blog-4",
    title: "Seasonal Viral Fevers & Dengue Awareness in Khammam",
    slug: "seasonal-viral-fevers-dengue-awareness-khammam",
    authorName: "Rithanya Medical Editorial",
    category: "Infectious Diseases",
    excerpt: "Warning signs of Dengue and Typhoid fevers, when to check platelets, and when to visit the 24/7 hospital emergency desk.",
    contentHtml:
      h("Do Not Wait Out a Persistent High Fever") +
      p("High fever lasting more than 48 hours accompanied by body ache, vomiting, or dizziness requires same-day blood parameter evaluation.") +
      ul(["Ensure plenty of fluids and ORS hydration", "Do not take over-the-counter painkillers like ibuprofen without medical advice", "Our 24/7 emergency desk is always ready with diagnostic testing"]),
    isPublished: true,
    publishedAt: new Date("2026-09-26T10:00:00.000Z"),
    sortOrder: 3,
    media: [{ id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" }],
  },
];

export const FALLBACK_PRODUCTS = [
  {
    id: "prod-1",
    name: "Digital Glucometer Kit",
    slug: "digital-glucometer-kit",
    category: "Diabetes Care",
    price: 899,
    stockUnits: 40,
    description: "Easy-read glucometer with lancing device, test strips, and carry case.",
    isPrescriptionReq: false,
    sortOrder: 0,
    media: [
      { id: "m-glucose-meter", url: "/seed/glucose-meter.webp", kind: "IMAGE" as const, originalName: "glucose-meter.webp" },
      { id: "m-glucose-finger", url: "/seed/glucose-finger.webp", kind: "IMAGE" as const, originalName: "glucose-finger.webp" },
    ],
  },
  {
    id: "prod-2",
    name: "Glucose Test Strips (50)",
    slug: "glucose-test-strips-50",
    category: "Diabetes Care",
    price: 749,
    stockUnits: 120,
    description: "Compatible blood sugar test strips, pack of 50.",
    isPrescriptionReq: false,
    sortOrder: 1,
    media: [{ id: "m-glucose-strips", url: "/seed/glucose-strips.webp", kind: "IMAGE" as const, originalName: "glucose-strips.webp" }],
  },
  {
    id: "prod-3",
    name: "Digital BP Monitor",
    slug: "digital-bp-monitor",
    category: "Senior Care",
    price: 1499,
    stockUnits: 25,
    description: "Automatic upper-arm digital blood pressure monitor with memory.",
    isPrescriptionReq: false,
    sortOrder: 2,
    media: [{ id: "m-nurse-bp", url: "/seed/nurse-bp.webp", kind: "IMAGE" as const, originalName: "nurse-bp.webp" }],
  },
  {
    id: "prod-4",
    name: "Fingertip Pulse Oximeter",
    slug: "fingertip-pulse-oximeter",
    category: "Wellness",
    price: 1199,
    stockUnits: 30,
    description: "Measure blood oxygen SpO2 and pulse rate in seconds.",
    isPrescriptionReq: false,
    sortOrder: 3,
    media: [{ id: "m-doctor-vitals", url: "/seed/doctor-vitals.webp", kind: "IMAGE" as const, originalName: "doctor-vitals.webp" }],
  },
  {
    id: "prod-5",
    name: "Oral Rehydration Salts (ORS) Pack",
    slug: "oral-rehydration-salts-ors-pack",
    category: "First Aid",
    price: 120,
    stockUnits: 200,
    description: "WHO-formula oral rehydration salts sachets, pack of 10.",
    isPrescriptionReq: false,
    sortOrder: 4,
    media: [{ id: "m-pharmacy-bottle", url: "/seed/pharmacy-bottle.webp", kind: "IMAGE" as const, originalName: "pharmacy-bottle.webp" }],
  },
  {
    id: "prod-6",
    name: "Sterile Dressing Kit",
    slug: "sterile-dressing-kit",
    category: "First Aid",
    price: 349,
    stockUnits: 60,
    description: "Sterile gauze pads, bandages, antiseptic, and medical tape for wound care.",
    isPrescriptionReq: false,
    sortOrder: 5,
    media: [{ id: "m-nurse-injection", url: "/seed/nurse-injection.webp", kind: "IMAGE" as const, originalName: "nurse-injection.webp" }],
  },
  {
    id: "prod-7",
    name: "Diabetic Nutrition Drink",
    slug: "diabetic-nutrition-drink",
    category: "Diabetes Care",
    price: 560,
    stockUnits: 50,
    description: "Scientifically balanced nutritional powder formulated for diabetic dietary support.",
    isPrescriptionReq: false,
    sortOrder: 6,
    media: [{ id: "m-pharmacy-shelves", url: "/seed/pharmacy-shelves.webp", kind: "IMAGE" as const, originalName: "pharmacy-shelves.webp" }],
  },
  {
    id: "prod-8",
    name: "Digital Thermometer",
    slug: "digital-thermometer",
    category: "Wellness",
    price: 199,
    stockUnits: 90,
    description: "Fast, accurate digital clinical thermometer with fever alert.",
    isPrescriptionReq: false,
    sortOrder: 7,
    media: [{ id: "m-pharmacy-counter", url: "/seed/pharmacy-counter.webp", kind: "IMAGE" as const, originalName: "pharmacy-counter.webp" }],
  },
];

export const FALLBACK_FACILITIES = [
  {
    id: "fac-1",
    title: "24/7 Emergency & Observation Wing",
    slug: "24-7-emergency-and-observation-wing",
    shortSummary: "Round-the-clock emergency care, rapid triage, trauma stabilization, observation beds and IV hydration therapy.",
    contentHtml:
      h("Round-the-Clock Emergency Response") +
      p("Our emergency department operates 24/7, 365 days a year with dedicated medical officers, critical care trained nursing staff, continuous vitals monitoring, and observation beds.") +
      ul([
        "24/7 emergency triage and acute medical stabilization",
        "Dedicated observation beds with multi-parameter monitors",
        "Rapid IV hydration and emergency medication administration",
        "Direct link to diagnostic laboratory and round-the-clock pharmacy",
      ]),
    sortOrder: 0,
    media: [
      { id: "m-building-ext", url: "/seed/rithanya-hospital-khammam-building-exterior-signboard.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-building-exterior-signboard.webp" },
      { id: "m-main-entrance", url: "/seed/rithanya-hospital-khammam-main-entrance-reception.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-main-entrance-reception.webp" },
    ],
  },
  {
    id: "fac-2",
    title: "Daycare Blood Transfusion Centre",
    slug: "daycare-blood-transfusion-centre",
    shortSummary: "Sanitised, family-friendly daycare transfusion unit with dedicated nursing, blood warmer technology, and saline flush protocols.",
    contentHtml:
      h("Safe, Sanitised Transfusion Protocols") +
      p("Rithanya Hospital is renowned across Khammam for its compassionate Daycare Transfusion Centre, providing scheduled blood transfusions for Thalassemia, Sickle Cell, and severe anaemia patients in a comfortable environment.") +
      ul([
        "Pre-transfusion screening and blood cross-matching verification",
        "Bedside nursing with real-time temperature and pulse monitoring",
        "Post-transfusion hydration and ferritin level tracking",
        "Subsidized and charitable care coordination",
      ]),
    sortOrder: 1,
    media: [
      { id: "m-children-day", url: "/seed/rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-childrens-day-celebration-group-photo.webp" },
      { id: "m-child-plant", url: "/seed/rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-child-gifted-plant-with-doctor.webp" },
    ],
  },
  {
    id: "fac-3",
    title: "In-House Diagnostic Laboratory",
    slug: "in-house-diagnostic-laboratory",
    shortSummary: "Automated clinical biochemistry, hematology, HbA1c testing, blood grouping and infectious disease serology with rapid turnaround.",
    contentHtml:
      h("Precision Laboratory Diagnostics") +
      p("Equipped with automated hematology analyzers, biochemistry platforms, and electrolyte testers to deliver accurate diagnostic reports within hours.") +
      ul([
        "Automated CBC, Hemoglobin electrophoresis, and blood smear testing",
        "HbA1c, lipid profiles, renal function, and liver enzyme panels",
        "Rapid serological testing for Dengue, Malaria, Typhoid, and Viral Fevers",
        "Computerized barcoded samples ensuring zero sample mix-ups",
      ]),
    sortOrder: 2,
    media: [
      { id: "m-lab-microscope", url: "/seed/lab-microscope.webp", kind: "IMAGE" as const, originalName: "lab-microscope.webp" },
      { id: "m-surgeon-xray", url: "/seed/rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-surgeon-reviewing-xray-reports.webp" },
    ],
  },
  {
    id: "fac-4",
    title: "Outpatient Department & Reception",
    slug: "outpatient-department-and-reception",
    shortSummary: "Spacious waiting areas, streamlined digital token registration, private consultation rooms and wheelchair assistance.",
    contentHtml:
      h("Patient-Centric Outpatient Experience") +
      p("Designed to minimize wait times and maximize patient comfort, our outpatient wing features comfortable waiting benches, wheelchair accessibility, and direct registration.") +
      ul([
        "Streamlined patient registration and digital case documentation",
        "Wheelchair accessibility with ramp entrances",
        "Private, air-cooled consultation rooms",
        "Courteous reception and helpline assistance",
      ]),
    sortOrder: 3,
    media: [
      { id: "m-opd-waiting", url: "/seed/rithanya-hospital-khammam-outpatient-waiting-area-registration.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-outpatient-waiting-area-registration.webp" },
      { id: "m-doc-consult", url: "/seed/rithanya-hospital-khammam-doctor-consulting-patient.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-doctor-consulting-patient.webp" },
    ],
  },
  {
    id: "fac-5",
    title: "24/7 Hospital Pharmacy",
    slug: "24-7-hospital-pharmacy",
    shortSummary: "Fully stocked on-site pharmacy dispensing authentic medications, diabetes care supplies, surgical consumables and 24-hour urgent prescriptions.",
    contentHtml:
      h("Round-the-Clock Medication Supply") +
      p("Located on the ground floor with direct outpatient and emergency access, ensuring patients receive genuine prescribed medications day or night.") +
      ul([
        "100% genuine medications, insulin, and cold-chain biologics",
        "Surgical disposables, dressing materials, and home care items",
        "Digital POS billing with UPI and card payment support",
        "Seamless prescription fulfillment directly from clinical consults",
      ]),
    sortOrder: 4,
    media: [
      { id: "m-pharmacy-shelves", url: "/seed/pharmacy-shelves.webp", kind: "IMAGE" as const, originalName: "pharmacy-shelves.webp" },
      { id: "m-pharmacy-counter", url: "/seed/pharmacy-counter.webp", kind: "IMAGE" as const, originalName: "pharmacy-counter.webp" },
    ],
  },
  {
    id: "fac-6",
    title: "Aarogyasri & Cashless Insurance Helpdesk",
    slug: "aarogyasri-and-cashless-insurance-helpdesk",
    shortSummary: "Dedicated liaison officers facilitating hassle-free documentation, eligibility verification, and pre-authorisation for PM-JAY, Aarogyasri, and TPAs.",
    contentHtml:
      h("Dedicated Patient Financial Assistance") +
      p("Our insurance facilitation desk guides patients through government schemes and private health insurance pre-authorisations with full transparency.") +
      ul([
        "Ayushman Bharat PM-JAY and Telangana Aarogyasri desk",
        "Private TPA cashless hospitalisation assistance",
        "Document collection, pre-auth submission, and claim tracking",
        "Zero-delay assistance for emergency admissions",
      ]),
    sortOrder: 5,
    media: [
      { id: "m-main-entrance", url: "/seed/rithanya-hospital-khammam-main-entrance-reception.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-main-entrance-reception.webp" },
      { id: "m-camp-desk", url: "/seed/rithanya-hospital-khammam-health-camp-registration-desk.webp", kind: "IMAGE" as const, originalName: "rithanya-hospital-khammam-health-camp-registration-desk.webp" },
    ],
  },
];

export const FALLBACK_BLOOD_STOCK = [
  { id: "stock-O", bloodGroup: "O+", groupCategory: "O", colorCode: "SKY_BLUE", wholeBloodUnits: 22, plasmaUnits: 14 },
  { id: "stock-A", bloodGroup: "A+", groupCategory: "A", colorCode: "YELLOW", wholeBloodUnits: 17, plasmaUnits: 11 },
  { id: "stock-B", bloodGroup: "B+", groupCategory: "B", colorCode: "RED", wholeBloodUnits: 14, plasmaUnits: 9 },
  { id: "stock-AB", bloodGroup: "AB+", groupCategory: "AB", colorCode: "WHITE", wholeBloodUnits: 6, plasmaUnits: 5 },
];
